! Seeds are chosen from the sequence generated by the logistic map. The
! parameters and initial values are chosen so as to generate a chaotic
! sequence which samples the space between 0 and 1
subroutine initializeSeeds(rseed, i, j, k, nx, ny)
  use arrayTools, only: sub2idx
  real(rkind), dimension(7), intent(inout) :: rseed
  integer, intent(in) :: i, j, k, nx, ny
  integer :: n, idx

  ! Set seed0
  do n = 1,size(rseed)
    rseed(n) = real(n,rkind)/initFact
  end do
  idx = sub2idx(i,j,k,nx,ny)

  ! Now compute seed(idx-1)
  do n = 1,idx-1
    call incrementLogisticMap(rseed)
  end do
end subroutine

subroutine updateSeeds(rseed,idx1,idx2)
  real(rkind), dimension(7), intent(inout) :: rseed
  integer, intent(in) :: idx1, idx2
  integer :: j

  do j = idx1,idx2-1
    call incrementLogisticMap(rseed)
  end do

end subroutine

subroutine incrementLogisticMap(x)
  real(rkind), dimension(7), intent(inout) :: x

  x = logMapFact*x*(1.d0 - x)

end subroutine
